export const uiText = {
  errors: {
    load: "Unable to load dashboard data",
    loadDetails: "Unable to load details",
    saveApplication: "Unable to save application changes",
    saveJob: "Unable to save job changes",
    saveEvidence: "Unable to resolve the review item",
    saveInsight: "Unable to save the interview note",
    fallback: "Unable to load dashboard",
    saveChanges: "Unable to save changes",
    refreshAfterSave: "Saved, but unable to refresh dashboard",
    reviewChanged: "Review items changed; refresh the queue and confirm again",
    documentUnavailable: "Document generation is unavailable on this Mac",
    documentGeneration: "Unable to generate application package",
    saveSearchSource: "Unable to save search source",
    openEmailDraft: "Unable to open a native Apple Mail reply. The draft text has been copied.",
    copyDraft: "Unable to copy the draft. Copy it manually instead.",
    noReplyableEmailThread: "No replyable email thread was found. Copy the draft instead."
  },
  nav: [
    { key: "today", label: "Today" },
    { key: "jobs", label: "Jobs" },
    { key: "pipeline", label: "Pipeline" },
    { key: "review", label: "Review" }
  ] as const,
  statuses: {
    not_applied: "Not applied",
    applied: "Applied",
    recruiter_screen: "Recruiter screen",
    technical_interview: "Technical interview",
    system_design: "System design",
    take_home: "Take-home task",
    onsite_final: "Onsite / final",
    offer: "Offer",
    rejected: "Rejected",
    withdrawn: "Withdrawn",
    unknown: "Unknown"
  } as Record<string, string>,
  review: {
    groups: {
      application_update: "Likely application update",
      rejection: "Likely rejection",
      recruiter_conversation: "Recruiter conversation",
      newsletter_alert: "Likely newsletter / job alert",
      unknown: "Unknown"
    },
    chooseAnother: "Choose another application",
    preserveStage: "If the email has no detected status, linking keeps the application's current stage unless you choose one.",
    searchApplications: "Search applications",
    searchQueue: "Search review items",
    filterGroup: "Filter group",
    bulkIgnore: "Bulk-ignore sender",
    bulkWarning: "Only the listed local review items will be resolved.",
    refreshQueue: "Refresh queue",
    cancel: "Cancel",
    noMatches: "No review items match these filters."
  },
  insightSources: {
    employer_feedback: "Employer feedback",
    system_inference: "System inference",
    user_note: "Your note"
  } as Record<string, string>,
  insightCategories: {
    react_typescript_fundamentals: "React / TypeScript fundamentals",
    react_native_mobile_architecture: "React Native / mobile architecture",
    system_design: "System design",
    coding_task: "Coding task",
    communication_leadership: "Communication / leadership",
    product_thinking: "Product thinking",
    language: "German / English",
    constraints: "Compensation, availability or location",
    reason_unknown: "Reason unknown"
  } as Record<string, string>,
  labels: {
    primaryNavigation: "Primary navigation",
    brand: "Job Search",
    operatingSystem: "Operating system",
    search: "Search",
    localSearch: "Local job search",
    planApplication: "Plan your next application",
    loading: "Loading pipeline…",
    appleMail: "Apple Mail · read-only import",
    applications: "applications",
    interviews: "interviews",
    offers: "offers",
    open: "Open",
    vacancy: "vacancy",
    linkUnavailable: "Link unavailable",
    followUp: "Follow-up",
    status: "Status",
    close: "Close",
    priority: "Priority",
    nextStep: "Next step",
    rejectionReason: "Rejection reason",
    appliedDate: "Applied date",
    decision: "Decision",
    decisionUnset: "Not decided",
    decisionApply: "Apply",
    decisionSkip: "Skip",
    decisionReview: "Review",
    notes: "Notes",
    save: "Save",
    saving: "Saving…",
    applicationDetails: "Application details",
    closeDetails: "Close details",
    details: "Details",
    detailsFor: "Details for",
    interviewTimeline: "Interview timeline",
    evidence: "Evidence and notes",
    addNote: "Add note",
    note: "Your interview note",
    noteCategory: "Note category",
    result: "Result",
    participants: "Participants",
    alreadyApplied: "Already applied",
    companyHistory: "Previous company history",
    restoreBlock: "Restore duplicate block",
    allowRepeat: "Allow repeat application",
    documents: "Documents",
    download: "Download",
    manualReview: "Needs manual review",
    reviewExplanation: "These emails were not allowed to change the pipeline because the system could not confidently match them. Choose exactly what each email means.",
    reviewReason: "Reason: low-confidence classification or no reliable application match.",
    reviewStatus: "Review status",
    existingApplication: "Existing application",
    chooseApplication: "Choose an application",
    linkApplication: "Link to application",
    company: "Company",
    role: "Role",
    createApplication: "Create application",
    notJobRelated: "Not job-related",
    detectedAs: "Detected as",
    confidence: "confidence",
    showing: "Showing",
    of: "of",
    items: "items",
    showMore: "Show 10 more",
    noReasonProvided: "No reason provided",
    applyToday: "Apply today",
    followUpToday: "Follow up today",
    needsAttention: "Needs attention",
    weeklyProgress: "Application progress",
    shortlist: "Shortlist",
    skip: "Skip",
    expire: "Expire",
    markApplied: "Mark as applied",
    openEmailDraft: "Open reply & copy draft",
    openingEmailDraft: "Opening reply…",
    replyReady: "Reply opened. Press ⌘V in Mail to paste the draft.",
    copyDraft: "Copy draft",
    draftText: "Draft text",
    done: "Done",
    snooze: "Snooze",
    snoozeUntil: "Snooze until",
    dismiss: "Dismiss",
    retry: "Retry",
    retryRefresh: "Retry refresh",
    documentLanguage: "Document language",
    generatePackage: "Generate application package",
    generatingPackage: "Generating package…",
    materials: "Materials",
    materialsFor: "Materials for",
    materialsDescription: "Create a local resume package for this job. This does not mark it as applied.",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    allTime: "All time",
    responses: "responses",
    todayResponseRate: "response rate",
    moreFollowUps: "more follow-ups due",
    reviewItem: "Review item",
    matchReason: "Match",
    context: "Context",
    detailsUnavailable: "Details unavailable",
    risk: "Check",
    roleRequirements: "Role requirements"
  },
  jobs: {
    new: "New",
    shortlisted: "Shortlisted",
    applied: "Applied",
    archived: "Skipped / expired",
    employment: "Employment type",
    role: "Role keywords (inferred)",
    workMode: "Work mode",
    minimum: "Minimum score",
    workingLinks: "Working links only",
    viewPipeline: "View in Pipeline",
    empty: "No jobs match these filters."
  },
  searchSources: {
    title: "Search sources",
    add: "Add source",
    edit: "Edit",
    enable: "Enable",
    disable: "Disable",
    disabled: "Disabled",
    open: "Open search",
    openFor: "Open search for",
    unavailable: "Search link unavailable",
    name: "Source name",
    url: "Filtered search URL",
    category: "Source category",
    enabled: "Enabled",
    save: "Save source",
    cancel: "Cancel",
    empty: "No search sources yet.",
    checked: "Last checked",
    success: "Last successful check",
    neverChecked: "Never checked",
    noSuccess: "No successful check",
    discovered: "discovered",
    imported: "imported",
    latestError: "Latest error",
    validationName: "Enter a source name.",
    validationUrl: "Enter an HTTP or HTTPS search URL.",
    categories: { permanent: "Permanent", freelance: "Freelance", both: "Both" }
  },
  pipeline: {
    active: "Active",
    archive: "Archive",
    daysInStage: "Days in stage",
    lastActivity: "Last activity",
    overdue: "Overdue",
    fromDate: "From date",
    emptyActive: "No active applications yet.",
    emptyArchive: "No archived applications match these filters.",
    overview: "Overview",
    nextAction: "Next action",
    activity: "Activity history",
    recruiterContact: "Recruiter contact",
    retryDetails: "Retry loading details",
    noEvidence: "No linked email evidence yet.",
    noActivity: "No activity yet."
  },
  empty: {
    followUps: "No overdue follow-ups.",
    interviews: "Interviews will appear after the Apple Mail import.",
    documents: "Select a job to create DOCX and PDF files.",
    review: "The review queue is empty.",
    applyToday: "No jobs need an application decision today.",
    needsAttention: "Nothing needs attention right now."
  }
} as const;
